### ISSUE TITLE
broken plans links

### ISSUE THREAD

**Issue by noamoss** [niryariv/opentaba-server#103]
broken  links from plans:

Misses  "/"+parameter symbol sign and ":" at the 2nd http[:]//  
i.e: 

1) http://mmi.gov.ilhttp//www.land.gov.il/IturTabotData%5Ctabot%5Cjerus%5C1014675_K.pdf.

2) http://mmi.gov.ilhttp//www.land.gov.il/IturTabotData%5Cnispachim%5Cjerus%5C1014282%5C100%5C%D7%97%D7%99%D7%A9%D7%95%D7%91%D7%99%20%D7%A9%D7%98%D7%97%D7%99%D7%9D.pdf

**Comment by florpor** [comment]
Fixed by #104 
@niryariv can I deploy and re-scrape?

**Comment by niryariv** [comment]
@florpor please go ahead - was hoping to do it today but got delayed by work + the newly arrived human at our household.

btw, if you feel like messing around with Docker, this might interest you: https://github.com/niryariv/opentaba-server/pull/100

**Comment by niryariv** [comment]
@florpor just noticed you're already there.. It's a high priority PR since building the server env locally is becoming a chore. If you want to go ahead and change it to Ubuntu etc & finalize it, please feel free to merge.

**Comment by florpor** [comment]
More fixes needed for this...
Server pull request #105
Client pull request https://github.com/niryariv/opentaba-client/pull/112

**Comment by niryariv** [comment]
feel free to merge

**Comment by florpor** [comment]
done deploying and re-scraping
