### ISSUE TITLE
Feeds are missing muni.display

### ISSUE THREAD

**Issue by noamoss** [niryariv/opentaba-server#106]
1) some of the general municipalities' feeds (i.e. [kiriat gat](http://opentaba-server-kiryatgat.herokuapp.com/plans.atom)) consist the muni name in the feed title, as they should. Others, (i.e. [Jerusalem](http://opentaba-server-jerusalem.herokuapp.com/plans.atom)) do not.

2) gush feeds title do not include muni name ([for example)](http://opentaba-server-jerusalem.herokuapp.com/gush/30053/plans.atom). 

Crucial for integrative usage of feeds.

**Comment by florpor** [comment]
@noamoss better?

**Comment by noamoss** [comment]
@florpor great! thanks.
