### ISSUE TITLE
what's the difference between fab refresh_db and renew_db?

### ISSUE THREAD

**Issue by niryariv** [niryariv/opentaba-server#94]
are they the same?

![screen shot 2014-12-30 at 1 08 36 pm](https://cloud.githubusercontent.com/assets/1771/5577942/38a23ff4-9025-11e4-97bf-42b448234786.png)

**Comment by florpor** [comment]
create_db (= renew_db) drops all the current collections and their data, and starts anew with the list of gushim.
update_db (= refresh_db) goes over the data in the db and the list of gushim, sees if there are any new ones in the list and adds them to the db without removing data, in case we grab a better gushim list from somewhere.
