### ISSUE TITLE
Mavat scraping and links don't work

### ISSUE THREAD

**Issue by florpor** [niryariv/opentaba-server#99]
Mavat changed their website (as we knew might happen).
Every current mavat link and the old search page now redirect here: http://moin.gov.il/Information/medatocnit4/Pages/default.aspx
So, besides all the links not working, mavat scraping doesn't work at the moment as well.

**Comment by florpor** [comment]
I guess the site is currently down...
All the links on the aforementioned page redirect back to itself.
Also, GIS gives:
![screen shot 2015-07-06 at 4 16 53 pm](https://cloud.githubusercontent.com/assets/1809093/8535442/ac1cb6a8-23fa-11e5-9c43-d396feaad8ff.png)

Might just be temporary and not require a fix on our part.

**Comment by niryariv** [comment]
ok, let's wait & see if they fix it

**Comment by florpor** [comment]
Site is back up, all the links and scraping work again...
